config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "overrides/registrations"}

  mount RailsAdmin::Engine => "/captainslounge", as: "rails_admin"
  mount Rapidfire::Engine => "/surveys"

  unauthenticated do
    root to: "home#index"
  end

  authenticated do
    root to: "home#dashboard", as: :authenticated_root
  end

  resources :users do
    member do
      get :achievements
    end
    resource :friendships do
      collection do
        post :search
      end
    end
  end
  resources :posts do
    resource :comments
  end
  resources :conversations
  resources :quests do
    collection do
      get :display
    end

    resources :missions do
      member do
        put :accept
        delete :cancel
        delete :reject
      end
    end
  end
  resources :bounties
  resources :leaderboard
  resources :rewards
  resource :like

  namespace :admin do
    resources :missions do
      collection do
        get :completed
        get :submitted
        get :accepted
      end
    end
    resources :bounties
  end

  get "/profile" => "users#profile", as: :profile
  get "/privacy" => "home#privacy", as: :privacy
  get "/about" => "home#about", as: :about
  get "/contact" => "home#contact", as: :contact


end

app/models/quest.rb
class Quest < ActiveRecord::Base

  geocoded_by :address do |object, results|
    if geo = results.first
      object.lat = geo.latitude
      object.long = geo.longitude
    end
  end
  after_validation :geocode, if: lambda { |obj| obj.address_changed? }

  validates :address, :title, :description, presence: true
  validates :level, numericality: { greater_than: 0 }

  has_and_belongs_to_many :rewards
  has_many :missions
  has_many :bounties

  def accept!(user)
    score = rewards.sum(:amount)
    user.update_attributes(score: user.score + score)
  end

  def display_rewards
    rewards.any? ? rewards.collect(&:description).to_sentence : "n/a"
  end

  def gold
    rewards.gold.any? ? rewards.gold.collect(&:description).to_sentence : "n/a"
  end

  def experience
    rewards.experience.any? ? rewards.experience.collect(&:description).to_sentence : "n/a"
  end

  def others
    rewards.others.any? ? rewards.others.collect(&:description).to_sentence : "n/a"
  end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  include ActivityManager
  before_action :authenticate_user!

  def index
  end

  def display
    latitude = params[:lat].to_f
    longitude = params[:long].to_f

    @completed_quests = current_user.missions.finished
    @accepted_quests = current_user.missions.current
    if current_user.mission_ids.present?
      @available_quests = Quest.where("level <= (?) AND id NOT IN (?) AND #{lat_lng_query(latitude, longitude)}", current_user.level, current_user.mission_ids)
    else
      @available_quests = Quest.where("level <= ? AND #{lat_lng_query(latitude, longitude)}", current_user.level)
    end

    @quests = Gmaps4rails.build_markers(@available_quests) do |quest, marker|
      marker.lat quest.lat
      marker.lng quest.long
      marker.infowindow infowindow(quest)

      if current_user.missions.collect(&:quest_id).include? quest.id
        marker.picture( { 
          url:    "http://gmapsmarkergenerator.eu01.aws.af.cm/getmarker?scale=1&color=00ff00",
          width:  22,
          height: 40
        })
      end
    end

    render partial: "tabs", layout: false
  end

private
  def infowindow(quest)
    "
      <h3> #{quest.title} </h3>
      <p> #{quest.description} </p>
      <hr/>
      <ul class='no-margin'>#{rewards(quest)}</ul>
      <div class='text-center'>
        #{view_quest(quest)}
      </div>
    "
  end

  def rewards(quest)
    "".tap do |str|
      quest.rewards.each do |reward|
        str << "<li>#{reward.description}</li>"
      end
    end
  end

  def view_quest(quest)
    if current_user.missions.collect(&:quest_id).include? quest.id
      "
        <a href='javascript:void(0)' disabled class='btn btn-sm btn-warning'>
          You are currently doing this quest!
        </a>
      "
    else
      "
        <a href='#available' aria-controls='list' role='tab' data-toggle='tab' class='btn btn-sm btn-primary'>
          View Quest Now!
        </a>
      "
    end
  end

  def lat_lng_query(latitude, longitude)
    "lat BETWEEN #{latitude - 1} AND #{latitude + 1} AND long BETWEEN #{longitude - 1} AND #{longitude + 1}"
  end
end

app/views/quests/_missions.haml
- if missions.any?
  %table.table.table-condensed.table-striped.table-hover.table-centered.table-bordered
    %thead
      %tr
        %th Title
        %th Description
        %th Status
        %th Gold
        %th Experience
        %th Rewards
        %th Actions
    %tbody
      - missions.each do |mission|
        %tr
          - quest = mission.quest
          %td= quest.title
          %td.description= quest.description
          %td= mission.status
          %td= quest.gold
          %td= quest.experience
          %td= quest.others
          %td
            - if mission.status == "In Review"
              = link_to quest_mission_path(quest, mission), data: { toggle: "modal", target: "#modal", placement: "top" }, role: "history-trigger", rel: "tooltip", title: "Show Images" do
                %i.fa.fa-eye
            - else
              = link_to edit_quest_mission_path(quest, mission), data: { toggle: "tooltip", placement: "top"}, title: "Submit for Review"  do
                %i.fa.fa-picture-o
            %span= "|"
            = link_to cancel_quest_mission_path(quest, mission), data: { toggle: "tooltip", placement: "top", confirm: "Are you sure?" }, title: "Cancel Quest", method: :delete do
              %i.fa.fa-remove

- else
  .alert.alert-info
    %i.fa.fa-info-circle
    You currently have no accepted quests.

app/views/quests/_quests.haml
- if quests.any?
  %table.table.table-condensed.table-striped.table-hover.table-centered.table-bordered
    %thead
      %tr
        %th Title
        %th Description
        %th Gold
        %th Experience
        %th Rewards
        %th Actions
    %tbody
      - quests.each do |quest|
        %tr
          %td= quest.title
          %td.description= quest.description
          %td= quest.gold
          %td= quest.experience
          %td= quest.others
          %td
            = link_to quest_missions_path(quest), method: :post, data: { toggle: "tooltip", placement: "top" }, title: "Accept" do
              %i.fa.fa-check-square
- else
  .alert.alert-info
    %i.fa.fa-info-circle
    There are no quests available.

app/views/quests/_tabs.haml
.tabpanel
  %ul.nav.nav-tabs{ role: "tablist" }
    %li.active{ role: "presentation" }
      %a{ href: "#map", aria: { controls: "map" }, role: "tab", data: { toggle: "tab" } } Quest Map
    %li{ role: "presentation" }
      %a{ href: "#completed", aria: { controls: "list" }, role: "tab", data: { toggle: "tab" } } Completed Quests
    %li{ role: "presentation" }
      %a{ href: "#accepted", aria: { controls: "list" }, role: "tab", data: { toggle: "tab" } } Accepted Quests
    %li{ role: "presentation" }
      %a{ href: "#available", aria: { controls: "list" }, role: "tab", data: { toggle: "tab" } } Available Quests



  .tab-content
    .tab-pane.active.quests#map{ role: "tabpanel" }
      #map-canvas

    .tab-pane.quests#completed{ role: "tabpanel" }
      .panel.panel-primary
        .panel-heading Completed Quests
        .panel-body 
          = render "quests/missions", missions: @completed_quests

    .tab-pane.quests#accepted{ role: "tabpanel" }
      .panel.panel-primary
        .panel-heading Accepted Quests
        .panel-body 
          = render "quests/missions", missions: @accepted_quests

    .tab-pane.quests#available{ role: "tabpanel" }
      .panel.panel-primary
        .panel-heading Available Quests
        .panel-body
          = render "quests/quests", quests: @available_quests

:javascript
  $(function(){
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        function(position) {
          handler = Gmaps.build("Google");
          handler.buildMap({ provider: { Zoom: 10, center: new google.maps.LatLng(position.coords.latitude, position.coords.longitude)}, internal: {id: 'map-canvas'}}, function(){
            markers = handler.addMarkers(#{raw @quests.to_json})
            handler.bounds.extendWith(markers);
          })
        }
      ) 
    } else {

    }
    RigPirate.Tooltip.init()
  })

app/views/quests/index.haml
%script{:src => "//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry", :type => "text/javascript"}
%script{:src => "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js", :type => "text/javascript"}

.row
  .col-lg-3.col-md-3.col-xs-3.sidebar
    = render "shared/sidebar"
  .col-lg-9.col-md-9.col-xs-9.central

:javascript

  $(function(){
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        function(position) {
          $.ajax({
            url: "/quests/display?lat=" + position.coords.latitude + "&long=" + position.coords.longitude,
            type: "GET",
            success: function(data) {
              $(".central").html(data)              
            }

          })
        }
      ) 
    } else {
      console.log("DIDN'T HAPPEN")
    }
    RigPirate.Tooltip.init()
  })