config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "overrides/registrations"}

  mount RailsAdmin::Engine => "/captainslounge", as: "rails_admin"
  mount Rapidfire::Engine => "/surveys"

  unauthenticated do
    root to: "home#index"
  end

  authenticated do
    root to: "home#dashboard", as: :authenticated_root
  end

  resources :users do
    member do
      get :achievements
    end
    resource :friendships do
      collection do
        post :search
      end
    end
  end
  resources :posts do
    resource :comments
  end
  resources :conversations
  resources :quests do
    collection do
      get :display
    end

    resources :missions do
      member do
        put :accept
        delete :cancel
        delete :reject
      end
    end
  end
  resources :bounties
  resources :leaderboard
  resources :rewards
  resource :like

  namespace :admin do
    resources :missions do
      collection do
        get :completed
        get :submitted
        get :accepted
      end
    end
    resources :bounties
  end

  get "/profile" => "users#profile", as: :profile
  get "/privacy" => "home#privacy", as: :privacy
  get "/about" => "home#about", as: :about
  get "/contact" => "home#contact", as: :contact


end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @conversations = current_user.mailbox.inbox.page(params[:page]).per(75)
  end

  def new
    @message = Messenger.new

    render partial: "form", layout: false if request.xhr?
  end

  def show
    @conversation = Mailboxer::Conversation.find(params[:id])
  end

  def create
    @message = Messenger.new(messenger_params.merge(current_user: current_user))

    if @message.save
      redirect_to conversations_path, notice: "Message has been sent!"
    else
      render :new
    end
  end

  def update
    @conversation = Mailboxer::Conversation.find(params[:id])

    if params[:condition] == "read"
      @conversation.mark_as_read current_user
    elsif params[:condition] == "unread"
      @conversation.mark_as_unread current_user
    end

    redirect_to conversations_path, notice: "Conversation has been updated"
  end

  def destroy
    @conversation = Mailboxer::Conversation.find(params[:id])

    @conversation.mark_as_deleted current_user

    redirect_to conversations_path, notice: "Conversation is now deleted!"
  end

  private
    def messenger_params
      params.require(:messenger).permit(:body, :conversation_id, recipient_ids: [])
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper

  def user_ids(conversation)
    [].tap do |array|
      array = conversation.recipients
      array.delete(current_user)
      return array
    end
  end

  def pull_right_if_mine(message)
    "pull-right" if message.sender == current_user
  end
end

app/views/conversations/_form.haml
.modal-content
  .modal-header
    %button.close{ data: { dismiss: "modal" } }
      %span= "&times;".html_safe
    %h4.modal-title New Message

  = reform_for @message, url: conversations_path do |f|
    = f.hidden_field :conversation_id, value: params[:conversation_id]
    .modal-body
      = f.input :recipient_ids, as: :select, choices: options_for_select(current_user.sanitized_friends, params[:user_ids]), html: {class: "form-control", placeholder: "Friends", role: "tagsinput", prompt: "Select User", multiple: true}
      = f.input :body, as: :text, class: "form-control", role: "autoexpand"

    .modal-footer
      %button.btn.btn-default{ data: { dismiss: "modal" } } Cancel
      = f.submit "Send", class: "btn btn-primary"

:javascript
  $(function(){
    RigPirate.Modals.close();
    RigPirate.Autoexpand.init();
    RigPirate.Tags.init();
  })

app/views/conversations/index.haml
.row
  .col-lg-3.col-md-3.col-xs-3.sidebar
    = render "shared/sidebar"
  .col-lg-9.col-md-9.col-xs-9.central
    .panel.panel-primary
      .panel-heading 
        Messages 
        .pull-right
          = link_to "New Message", new_conversation_path, role: "history-trigger", data: { toggle: "modal", target: "#modal" }, class: "btn btn-default btn-xs"

      .panel-body
        - if @conversations.present?
          %table.table.table-condensed.table-striped.table-hover.table-centered.table-bordered
            %thead
              %tr
                %th Sent By
                %th Last Message
                %th Sent On
                %th Actions
            %tbody
              - @conversations.each do |conversation|
                %tr
                  - last_message = conversation.last_message
                  %td
                    = link_to conversation_path(conversation) do
                      = last_message.sender.full_name
                  %td= last_message.body
                  %td= time_ago_in_words(last_message.created_at, include_seconds: true)
                  %td
                    = link_to conversation_path(conversation, { condition: "unread" } ), method: :put, data: { toggle: "tooltip", placement: "top" }, title: "Mark as Unread" do
                      %i.fa.fa-eye
                    %span= "|"
                    = link_to conversation_path(conversation, { condition: "read" } ), method: :put, data: { toggle: "tooltip", placement: "top" }, title: "Mark as Read" do
                      %i.fa.fa-eye-slash
                    %span= "|"
                    = link_to conversation_path(conversation), method: :delete, data: { toggle: "tooltip", placement: "top" }, title: "Delete Conversation" do
                      %i.fa.fa-trash-o

          .text-center
            = paginate @conversations
        - else
          .alert.alert-info
            %i.fa.fa-info-circle
            You currently have no messages.

:javascript
  $(function(){
    RigPirate.Tooltip.init()
  })

app/views/conversations/show.haml
.row
  .col-lg-3.col-md-3.col-xs-3.sidebar
    = render "shared/sidebar"
  .col-lg-9.col-md-9.col-xs-9.central
    .panel.panel-primary
      .panel-heading 
        Conversation between
        = @conversation.participants.collect(&:full_name).to_sentence
        .pull-right
          = link_to "New Message", new_conversation_path( conversation_id: @conversation.id, user_ids: user_ids(@conversation)), role: "history-trigger", data: { toggle: "modal", target: "#modal" }, class: "btn btn-default btn-xs" 
      .panel-body
        - @conversation.messages.each do |message|
          .col-xs-12.col-md-12.col-lg-12.message
            .holder{ class: "#{pull_right_if_mine(message)}" }
              %strong= message.sender.full_name
              %p= message.body
          .clearfix
          %hr