config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "overrides/registrations"}

  mount RailsAdmin::Engine => "/captainslounge", as: "rails_admin"
  mount Rapidfire::Engine => "/surveys"

  unauthenticated do
    root to: "home#index"
  end

  authenticated do
    root to: "home#dashboard", as: :authenticated_root
  end

  resources :users do
    member do
      get :achievements
    end
    resource :friendships do
      collection do
        post :search
      end
    end
  end
  resources :posts do
    resource :comments
  end
  resources :conversations
  resources :quests do
    collection do
      get :display
    end

    resources :missions do
      member do
        put :accept
        delete :cancel
        delete :reject
      end
    end
  end
  resources :bounties
  resources :leaderboard
  resources :rewards
  resource :like

  namespace :admin do
    resources :missions do
      collection do
        get :completed
        get :submitted
        get :accepted
      end
    end
    resources :bounties
  end

  get "/profile" => "users#profile", as: :profile
  get "/privacy" => "home#privacy", as: :privacy
  get "/about" => "home#about", as: :about
  get "/contact" => "home#contact", as: :contact


end

app/models/reward.rb
class Reward < ActiveRecord::Base
  has_and_belongs_to_many :quests

  validates :name, :description, :amount, :category, presence: true
  
  scope :experience, -> { where(category: "Experience" ) }
  scope :gold, -> { where(category: "Gold" ) }
  scope :others, -> { where(category: "Others" ) }
  scope :purchaseable_by_gold, -> { where(purchaseable: true) }

  def experience?
    category == "Experience"
  end
  
  def gold?
    category == "Gold"
  end

  def purchase!(user)
    if user.total_gold >= self.purchaseable_for
      Bounty.create(
        name:       self.name,
        amount:     self.amount,
        category:   self.category,
        status:     "Requested",
        user_id:    user.id)

      user.update_attributes(gold_spent: user.gold_spent + self.purchaseable_for)
    end
  end

  rails_admin do
    field :name
    field :description
    field :amount
    field :category, :enum do
      enum do
        ["Experience", "Gold", "Others"]
      end
    end
    field :quests
    field :purchaseable
    field :purchaseable_for
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @purchaseable_rewards = Reward.purchaseable_by_gold
    @rewards = current_user.bounties.others.page(params[:page]).per(75)
  end

  def update
    @reward = Reward.find(params[:id])

    if @reward.purchase!(current_user)
      redirect_to rewards_path, notice: "Purchase has been completed. An admin will send you the reward shortly."
    else
      redirect_to rewards_path, alert: "You have insufficent funds."
    end
  end
end

app/views/rewards/_reward_table.haml
%table.table.table-condensed.table-striped.table-hover.table-centered.table-bordered
  %thead
    %tr
      %th Reward Name
      %th Amount
      %th Actions
  %tbody
    - rewards.each do |reward|
      %tr
        %td= reward.name
        %td= reward.purchaseable_for
        %td
          = link_to reward_path(reward), data: { toggle: "tooltip", placement: "top" }, title: "Buy Reward", method: :put do
            %i.fa.fa-check-square

app/views/rewards/_table.haml
- if rewards.any?
  %table.table.table-condensed.table-striped.table-hover.table-centered.table-bordered
    %thead
      %tr
        %th Reward Name
        %th Amount
        %th Status
        %th Actions
    %tbody
      - rewards.each do |reward|
        %tr
          %td= reward.name
          %td= reward.amount
          %td= reward.status
          %td
            - unless reward.status == "Requested"
              = link_to bounty_path(reward), data: { toggle: "tooltip", placement: "top" }, title: "Claim Reward", method: :put do
                %i.fa.fa-check-square

  .text-center
    = paginate @rewards
- else
  .alert.alert-info
    %i.fa.fa-info-circle
    You don't have any rewards as of right now.

app/views/rewards/index.haml
.row
  .col-lg-3.col-md-3.col-xs-3.sidebar
    = render "shared/sidebar"
  .col-lg-9.col-md-9.col-xs-9.central
    .panel.panel-primary
      .panel-heading Purchaseable Rewards
      .panel-body
        - if @purchaseable_rewards.present?
          = render "reward_table", rewards: @purchaseable_rewards
        - else
          .alert.alert-info
            %i.fa.fa-info-circle
            There are no purchaseable rewards

    .panel.panel-primary
      .panel-heading Claimable Rewards
      .panel-body
        - if @rewards.present?
          = render "table", rewards: @rewards
        - else
          .alert.alert-info
            %i.fa.fa-info-circle
            You currently have no rewards.

:javascript
  $(function(){
    RigPirate.Tooltip.init()
  })