config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "overrides/registrations"}

  mount RailsAdmin::Engine => "/captainslounge", as: "rails_admin"
  mount Rapidfire::Engine => "/surveys"

  unauthenticated do
    root to: "home#index"
  end

  authenticated do
    root to: "home#dashboard", as: :authenticated_root
  end

  resources :users do
    member do
      get :achievements
    end
    resource :friendships do
      collection do
        post :search
      end
    end
  end
  resources :posts do
    resource :comments
  end
  resources :conversations
  resources :quests do
    collection do
      get :display
    end

    resources :missions do
      member do
        put :accept
        delete :cancel
        delete :reject
      end
    end
  end
  resources :bounties
  resources :leaderboard
  resources :rewards
  resource :like

  namespace :admin do
    resources :missions do
      collection do
        get :completed
        get :submitted
        get :accepted
      end
    end
    resources :bounties
  end

  get "/profile" => "users#profile", as: :profile
  get "/privacy" => "home#privacy", as: :privacy
  get "/about" => "home#about", as: :about
  get "/contact" => "home#contact", as: :contact


end

app/views/shared/_footer.haml
%footer
  .container
    %ul.nav.navbar-nav.footer-nav
      %li
        %small= link_to "Privacy Policy", privacy_path
      %li
        %small= link_to "About Us", about_path
      %li
        %small= link_to "Contact Us", contact_path
    .pull-right
      %small &copy; 2015 All Rights Reserved.
    

app/views/shared/_header.haml
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      - if user_signed_in?
        = link_to "RigPirate" , root_path, class: "navbar-brand"
      - else
        = link_to "RigPirate" , authenticated_root_path, class: "navbar-brand"
    .navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          - if current_user.admin?
            %li= link_to "Survey", rapidfire_path
            %li= link_to "Admin",  admin_missions_path
          %li= link_to "Leaderboard", leaderboard_index_path
          %li= link_to "New Post", new_post_path, role: "history-trigger", data: { toggle: "modal" , target: "#modal" }
          %li= link_to "Log Out", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Sign up", new_user_registration_path
          %li= link_to "Login", new_user_session_path

app/views/shared/_messages.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-dismissable notifications alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

:javascript
  $(function(){ RigPirate.Alerts.fadeOut() })

app/views/shared/_modal.haml
.modal.fade#modal
  .modal-dialog

app/views/shared/_sidebar.haml
%section.profile
  .row
    .col-lg-12.col-xs-12.col-md-12
      .col-lg-4.col-md-12.col-xs-12.text-center
        = render "users/avatar", user: @user ||= current_user
      .col-lg-8.col-md-12.col-xs-12.name.text-center
        - if owner?
          %p Welcome,
        - else
          %p Viewing,
        %p= @user.full_name
        %p
          %small
            Level 
            = @user.level
        %p
          %small
            ( Exp
            = @user.score
            )
        %p
          %small
            ( Gold 
            = @user.total_gold
            )



%section.navigation
  %ul
    - if owner?
      %li= link_to "View Profile", profile_path
      %li= link_to "Edit Profile", edit_user_path(current_user), role: "history-trigger", data: { toggle: "modal", target: "#modal" }
      %li= link_to "Rewards", rewards_path
      %li= link_to "Quests", quests_path
      %li= link_to "Achievements", achievements_user_path(current_user)
      %li= link_to "Messages", conversations_path
      %li= link_to "Friends", user_friendships_path(current_user)
    - else
      = render "friendship", current_user: current_user, another_user: @user